//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int TaskId { get; set; }
        public string Body { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int StatusId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
