//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int TaskId { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
        public int StatusId { get; set; }
        public int PriorityId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool Deleted { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ref_Priorities ref_Priorities { get; set; }
        public virtual ref_Status ref_Status { get; set; }
        public virtual UserProfileM UserProfile { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
