//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileM
    {
        public UserProfileM()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
